### ISSUE TITLE
CLI doesn't install dependencies

### ISSUE THREAD

**Issue by Hardenberg** [plusnew/cli#2]
1. cli@beta installed global 
2. clear folder 
--> 
`npx @plusnew/cli@beta test_2`
`npx: installed 1 in 1.932s`

result: package.json
`{
  "name": "test_2",
  "version": "1.0.0",
  "description": "",
  "main": "dist/app.js",
  "scripts": {
    "start": "webpack-dev-server --env.mode=development",
    "build": "webpack --env.mode=production",
    "test": "jest",
    "test:watch": "jest --watch"
  },
  "keywords": [
    "plusnew"
  ],
  "author": ""
}`
an `npm start` -> no dependencies installed

Enviroment: Win10, npm: 6.13.7

**Comment by plusgut** [comment]
Thanks for reporting that bug, I'll take care of it.

Until then I would recommend that you install the missing dependencies by hand.
Here is the list of needed dependencies: https://github.com/plusnew/cli/blob/master/tasks/npm.js

**Comment by Hardenberg** [comment]
thank u :) the workaround works:)

**Comment by plusgut** [comment]
fixed, cli doesn`t install dependencies anymore. just adds the package.json and yarn.lock
